### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by kuraydev** [STRRL/serverless-github-badges#1]
Hey @STRRL 

Great alternative :) Thank you for that. 

I could not make the customization. It simply not working with the old way. I am trying to use this 
```
?style=for-the-badge&color=eb1b0c
```
But nothing changes. Do you think I should add it differently?

**Comment by STRRL** [comment]
I hard-coded the style when I wrote the codes at first.

I would try to update that.

**Comment by STRRL** [comment]
Updated in 69019daad07ad2f4ed5bf22c2bc89bd3e5825d11 ❤️

**Comment by STRRL** [comment]
I see that it works on your GitHub Profile! 
<img width="201" alt="image" src="https://user-images.githubusercontent.com/20221408/177584249-20e5507f-d919-4c11-adb6-f6729414a725.png">


I am going to close this issue.  Fell free to reopen it if you face other related problems :)
